apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: ilo2.etl.rht-labs.com
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: demo-infra
  name: ilo2.etl.rht-labs.com
  namespace: demo-infra
spec:
  bmc:
    address: "idrac-virtualmedia://10.9.48.212/redfish/v1/Systems/System.Embedded.1"
    credentialsName: drac-credentials
    disableCertificateVerification: true
  bootMACAddress: "3C:AD:05:67:B9:0C"
  online: true