apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: master1.ocp4.example.com
    bmac.agent-install.openshift.io/role: master
  labels:
    infraenvs.agent-install.openshift.io: demo-infra
  name: master1.ocp4.example.com
  namespace: demo-infra
spec:
  bmc:
    address: "idrac-virtualmedia://mgmt-x37-h35-000-r740xd.rdu3.labs.perfscale.redhat.com/redfish/v1/Systems/System.Embedded.1"
    credentialsName: drac-credentials
    disableCertificateVerification: true
  bootMACAddress: "3C:FD:FE:C4:F0:50"
  online: true
