apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/kube-ops-view/

patches:

  - patch: |-
      - op: replace
        path: /spec/href
        value: "https://kube-ops-view-kube-ops-view.apps.demo-cluster.rht-labs.com"
    target:
      kind: ConsoleLink
      name: kube-ops-view-link
      namespace: kube-ops-view