apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    storageClassName: csi-cinder-sc-retain
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    storageClassName: csi-cinder-sc-retain
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  imageStorage:
    storageClassName: csi-cinder-sc-retain
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi