applications:

  ansible-automation-platform-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: aap
    source:
      path: clusters/hub/overlays/ansible-automation-platform-operator 

  ansible-automation-platform-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: aap
    source:
      path: clusters/hub/overlays/ansible-automation-platform-configuration       

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-operator      

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-configuration     

  acm-central-infrastructure-management-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-central-infrastructure-management-config

  patch-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: patch-operator
    source:
      path: clusters/hub/overlays/patch-operator   

  demo-infra:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '35'
    destination:
      namespace: demo-infra
    source:
      path: clusters/hub/overlays/demo-infra                    
                          