apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: cluster-deployment
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline:  
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVnOEYFaN6tp/CXn5aBgD5YZbbwJHhUYbAahoGz3IbP8YZZwyBvJvgy9CujKTaIpZHweYRwMEtvPaX65g8AQDd8t6Gqc+JVJue6HTqrawH2wvq8Qdhip9L09fK2WqtP7UbVF+fgiwm9kebajkAqtlOttcdHipeRy5TGVE2hbV1zqc6UjTo6lKzxflm2Jd5EMc4TZCleSFApBod+jgFZoke/8Q/GHWyQs7YaoE3h/JND7z6aye5HoAPQBT18y/4Amwj7h2hIcIsSJ8JAHsOZ0NB4gz1qwpkG/dYAYV1iARM/+qnZ7EJAt4DofqUAS1/0BdXK+1RL8uI0db4r8U3pTe+oFGORQHRNa+ehDoX1PdOU+o59OmjEaJpcq0YRB3NqOwfZzATUfOqcZswH0xC6WKi/UknBFPgJv6JfD0+dee/kWTmgFrzT6Ie9hRql2bA+qjSoPfWzPk+Gv1Wuf6UGdC2DpKPO+vOhVzRtog/cvwjGSJv5p2X6biRGiYy8a0bX0= rspazzol@rspazzol
      location: demo-infra
      workers: 0
      masters: 3
      ingressVIP: 10.1.196.48
      apiVIP: 10.1.196.49
      clusterSet: default
      baseDomain: demo-cluster.rht-labs.com
      automaticHostBinding: true
      hostNames:
      - ilo1.etl.rht-labs.com
      - ilo1.et2.rht-labs.com
      - ilo1.et3.rht-labs.comm
  - name: cluster-registration
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline: 
      clusterSet: default
      repoURL: https://github.com/raffaelespazzoli/e2e-baremetal-provisioning.git
      labels:
        cloud: BareMetal
        vendor: OpenShift                