apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: cluster-deployment
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline:  
      location: demo-infra
      workers: 0
      masters: 3
      ingressVIP: 10.1.196.48
      apiVIP: 10.1.196.49
      clusterSet: default
      baseDomain: demo-cluster.rht-labs.com
      automaticHostBinding: true
      hostNames:
      - ilo1.etl.rht-labs.com
      - ilo1.et2.rht-labs.com
      - ilo1.et3.rht-labs.comm
  - name: cluster-registration
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline: 
      clusterSet: default
      repoURL: https://github.com/raffaelespazzoli/e2e-baremetal-provisioning.git
      labels:
        cloud: BareMetal
        vendor: OpenShift                