apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: cluster-deployment
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline:  
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD1iL9/XVz0a/dJ2lYyAnxCc5lbeark2gHcXDLKXDo9+zJlJ4uVAzMpv0ijV2nAMkFOELJDgvCuKzmwtuv31PhHxnnB4SOPVaOyJtmVhVJIJ4cQWxxrELDhJDgcE1fTR1jZPa3lDleq1nPp6hkAfh9li+/8RwKwalcbu91jWVD0a9vzyYhSf2e+6UtbIINFEmY+Bnnou970EBfBVB4NSool9urXsIJuhhxCuL0A+131a5mMEN4G6KxbNFdmkfPbbUvFEmFCeDiYi63r0vnOXIxrjjZV8Zqc2XW/WfNqJfJaNzfshgqoo9tVm9utgN0/C5pb1GUqRgyb5Buvrlv6wzhUaTcGZBeMRi/mrjHXkxMzj6vp6C/vE8wy1LGp78mnCtRQM88eCTLpt9jyk/rwVi4g1dTugV54Zq/M8g+BEo7e744QaYeKIuyIrdgMytzAANramA0lpDc8igviNTG77vkAxfqWB6fRJ+Zc07uUDO3BonhMIg/FXOJ8Xz47kTIpBSlr/KszpFYTCfEXjZqJisItv+NCNMJ8tbRr7/TQAkx8W+8qCNNxVeCjEqTLYFZari6W0S2EpyeoUjxOPb+SosqNnbHlElw/yx5nB3zSrK0klRrbb34mxpFM7JTWE6vr9GogE9Yc6QnSwMU12iRRU2maCgsIR4pD1tjpVpVk3Op8tQ==
      location: demo-infra
      workers: 0
      masters: 3
      ingressVIP: 192.168.127.200
      apiVIP: 192.168.127.201
      clusterSet: default
      baseDomain: example.com
      automaticHostBinding: true
      hostNames:
      - master0.ocp4.example.com
      - master1.ocp4.example.com
      - master2.ocp4.example.com
  - name: cluster-registration
    releaseName: demo-cluster
    namespace: demo-cluster
    valuesInline: 
      clusterSet: default
      repoURL: https://github.com/machacekondra/e2e-baremetal-provisioning.git
      labels:
        cloud: BareMetal
        vendor: OpenShift                
